spring:
  profiles:
    active: dev
  application:
    name: crm-bh
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%class{50}.%M:%L) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    ru.filit.mdma.crm-bh: DEBUG
  file:
    name: "crm-bh/logs/application-debug.log"
server:
  port: 8080